name: "Build gem to rubygems.org"
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: "git"
        uses: actions/checkout@v2
      - name: "publishing gem"
        env:
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${RUBYGEMS_API_KEY}\n" > $HOME/.gem/credentials
          cd $GITHUB_WORKSPACE
          gem build *.gemspec
          gem push *.gem
